router id 10.69.0.4;

log stderr all;

protocol device {
    scan time 10;
}

protocol static nodeaddr {
    ipv4 {};
    route 10.69.0.4/32 via "lo";
}

protocol kernel {
    merge paths;
    ipv4 {
        export filter {
            if source = RTS_DEVICE then reject;
            if proto = "coil" then reject;
            if (64698,64699) ~ bgp_community then reject;
            if (64798,64799) ~ bgp_community then reject;
            accept;
        };

    };
}

ipv4 table coiltab;

protocol kernel 'coil' {
    kernel table 119;  # coil exports
    learn;
    scan time 1;
    ipv4 {
        table coiltab;
        import all;
        export none;
    };
}

protocol pipe {
    table master4;
    peer table coiltab;
    import all;
    export none;
}

ipv4 table dummytab;

protocol static dummystatic {
    ipv4 { table dummytab; };
    route 0.0.0.0/0 via "lo";
}

protocol bgp tor {
  local as 65001;
  neighbor 10.69.0.1 as 65001;

  direct;
  error wait time 3,300;
  ipv4 {
    # Accept routes regardless of its NEXT_HOP.
    # igp table dummytab;
    gateway recursive;
    next hop self;

    import filter {
      # If this route came from iBGP peers,
      if bgp_next_hop.mask(26) = from.mask(26) then {
        # use the NEXT_HOP as the gateway address.
        gw = bgp_next_hop;
          accept;
      }
      # Otherwise, use the router address as the gateway address.
      # This is virtually equal to "next hop self" on receiver side.
      gw = from;
      accept;
    };

    export all;
  };

}

protocol bgp cilium {
    local as 64699;
    neighbor 127.0.0.1 as 64698;

    multihop;
    passive;
    ipv4 {
        import filter {
            bgp_community.add((64698,64699));
            accept;
        };
        export none;
    };
}

protocol bgp mooring {
    local as 64799;
    neighbor 127.0.0.2 as 64798;

    multihop;
    passive;
    ipv4 {
        import filter {
            bgp_community.add((64798,64799));
            accept;
        };
        export none;
    };
}
