apiVersion: coil.cybozu.com/v2
kind: AddressPool
metadata:
  name: default
spec:
  blockSizeBits: 5
  subnets:
  - ipv4: 10.64.0.0/16
---
apiVersion: coil.cybozu.com/v2
kind: AddressPool
metadata:
  name: internet-egress
spec:
  blockSizeBits: 0
  subnets:
  - ipv4: 172.190.0.0/28
---
apiVersion: coil.cybozu.com/v2
kind: AddressPool
metadata:
  name: domestic-egress
spec:
  blockSizeBits: 0
  subnets:
    - ipv4: 192.168.0.0/26
---
apiVersion: coil.cybozu.com/v2
kind: AddressPool
metadata:
  name: domestic1-egress
spec:
  blockSizeBits: 0
  subnets:
    - ipv4: 192.168.10.0/26
