//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATConfig) DeepCopyInto(out *NATConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATConfig.
func (in *NATConfig) DeepCopy() *NATConfig {
	if in == nil {
		return nil
	}
	out := new(NATConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATConfigList) DeepCopyInto(out *NATConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NATConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATConfigList.
func (in *NATConfigList) DeepCopy() *NATConfigList {
	if in == nil {
		return nil
	}
	out := new(NATConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATConfigSpec) DeepCopyInto(out *NATConfigSpec) {
	*out = *in
	if in.ExternalIPPool != nil {
		in, out := &in.ExternalIPPool, &out.ExternalIPPool
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TargetCIDRs != nil {
		in, out := &in.TargetCIDRs, &out.TargetCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PodSelector.DeepCopyInto(&out.PodSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATConfigSpec.
func (in *NATConfigSpec) DeepCopy() *NATConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NATConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRange) DeepCopyInto(out *NATPortRange) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRange.
func (in *NATPortRange) DeepCopy() *NATPortRange {
	if in == nil {
		return nil
	}
	out := new(NATPortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATPortRange) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeList) DeepCopyInto(out *NATPortRangeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NATPortRange, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeList.
func (in *NATPortRangeList) DeepCopy() *NATPortRangeList {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATPortRangeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeRequest) DeepCopyInto(out *NATPortRangeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeRequest.
func (in *NATPortRangeRequest) DeepCopy() *NATPortRangeRequest {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATPortRangeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeRequestList) DeepCopyInto(out *NATPortRangeRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NATPortRangeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeRequestList.
func (in *NATPortRangeRequestList) DeepCopy() *NATPortRangeRequestList {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NATPortRangeRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeRequestSpec) DeepCopyInto(out *NATPortRangeRequestSpec) {
	*out = *in
	if in.PortRangeCount != nil {
		in, out := &in.PortRangeCount, &out.PortRangeCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeRequestSpec.
func (in *NATPortRangeRequestSpec) DeepCopy() *NATPortRangeRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeRequestStatus) DeepCopyInto(out *NATPortRangeRequestStatus) {
	*out = *in
	if in.DeletionGracePeriodExpiry != nil {
		in, out := &in.DeletionGracePeriodExpiry, &out.DeletionGracePeriodExpiry
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeRequestStatus.
func (in *NATPortRangeRequestStatus) DeepCopy() *NATPortRangeRequestStatus {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATPortRangeSpec) DeepCopyInto(out *NATPortRangeSpec) {
	*out = *in
	if in.TargetCIDRs != nil {
		in, out := &in.TargetCIDRs, &out.TargetCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Allocations != nil {
		in, out := &in.Allocations, &out.Allocations
		*out = make([]PortAllocation, len(*in))
		copy(*out, *in)
	}
	if in.StaleSince != nil {
		in, out := &in.StaleSince, &out.StaleSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATPortRangeSpec.
func (in *NATPortRangeSpec) DeepCopy() *NATPortRangeSpec {
	if in == nil {
		return nil
	}
	out := new(NATPortRangeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortAllocation) DeepCopyInto(out *PortAllocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortAllocation.
func (in *PortAllocation) DeepCopy() *PortAllocation {
	if in == nil {
		return nil
	}
	out := new(PortAllocation)
	in.DeepCopyInto(out)
	return out
}
