apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
  serviceSubnet: 10.68.0.0/16
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    kubernetesVersion: "v1.34.8"
    scheduler:
      extraVolumes:
        - name: "config"
          hostPath: /node/scheduler
          mountPath: /var/lib/scheduler
          readOnly: true
      extraArgs:
        config: /var/lib/scheduler/scheduler-config.yaml
    controllerManager:
      extraArgs:
        "v": "5"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.0.2"
      localAPIEndpoint:
        advertiseAddress: "10.69.0.2"
    extraMounts:
      - containerPath: /var/lib/kubelet
        hostPath: /tmp/topolvm/controller
        propagation: Bidirectional
      - containerPath: /dev
        hostPath: /dev
      - hostPath: node
        containerPath: /node
    labels:
      cke.cybozu.com/rack: 0
      cke.cybozu.com/register-month: "2025-03"
      cke.cybozu.com/retire-month: "2030-03"
      cke.cybozu.com/role: cs
      cke.cybozu.com/master: "true"
      sabakan.cke.cybozu.com/datacenter: local
      sabakan.cke.cybozu.com/machine-type: local-cs-1
      sabakan.cke.cybozu.com/product: local
      topology.kubernetes.io/zone: rack0
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.0.3"
    extraMounts:
      - containerPath: /run/topolvm
        hostPath: /tmp/topolvm/lvmd1
      - containerPath: /var/lib/kubelet
        hostPath: /tmp/topolvm/worker1
        propagation: Bidirectional
      - containerPath: /dev
        hostPath: /dev
      - hostPath: node
        containerPath: /node
    labels:
      cke.cybozu.com/rack: 0
      cke.cybozu.com/register-month: "2025-03"
      cke.cybozu.com/retire-month: "2030-03"
      cke.cybozu.com/role: cs
      sabakan.cke.cybozu.com/datacenter: local
      sabakan.cke.cybozu.com/machine-type: local-cs-1
      sabakan.cke.cybozu.com/product: local
      topology.kubernetes.io/zone: rack0
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.1.2"
    extraMounts:
      - containerPath: /run/topolvm
        hostPath: /tmp/topolvm/lvmd2
      - containerPath: /var/lib/kubelet
        hostPath: /tmp/topolvm/worker2
        propagation: Bidirectional
      - containerPath: /dev
        hostPath: /dev
      - hostPath: node
        containerPath: /node
    labels:
      cke.cybozu.com/rack: 1
      cke.cybozu.com/register-month: "2025-03"
      cke.cybozu.com/retire-month: "2030-03"
      cke.cybozu.com/role: cs
      sabakan.cke.cybozu.com/datacenter: local
      sabakan.cke.cybozu.com/machine-type: local-cs-1
      sabakan.cke.cybozu.com/product: local
      topology.kubernetes.io/zone: rack1
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.2.2"
    extraMounts:
      - containerPath: /run/topolvm
        hostPath: /tmp/topolvm/lvmd3
      - containerPath: /var/lib/kubelet
        hostPath: /tmp/topolvm/worker3
        propagation: Bidirectional
      - containerPath: /dev
        hostPath: /dev
      - hostPath: node
        containerPath: /node
    labels:
      cke.cybozu.com/rack: 2
      cke.cybozu.com/register-month: "2025-03"
      cke.cybozu.com/retire-month: "2030-03"
      cke.cybozu.com/role: cs
      sabakan.cke.cybozu.com/datacenter: local
      sabakan.cke.cybozu.com/machine-type: local-cs-1
      sabakan.cke.cybozu.com/product: local
      topology.kubernetes.io/zone: rack2
containerdConfigPatches:
  - |
    [debug]
      level = "info"
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/node/containerd/conf.d"
