apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
spec:
  blocks:
  - cidr: 10.72.32.0/20
  serviceSelector:
    matchExpressions:
      - {key: "lbipam.neco.cybozu.io/address-pool", operator: NotIn, values: ["internet", "internet-cn", "bastion"]}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: bastion
spec:
  blocks:
  - cidr: 10.72.48.48/28
  serviceSelector:
    matchExpressions:
      - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["bastion"]}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: internet
spec:
  blocks:
  - cidr: 172.190.0.16/28
  serviceSelector:
    matchExpressions:
      - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["internet"]}
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: internet-cn
spec:
  blocks:
  - cidr: 172.190.0.248/29
  serviceSelector:
    matchExpressions:
      - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["internet-cn"]}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  # Enable BGP speaker on CS nodes, excluding spare nodes.
  nodeSelector:
    matchExpressions:
      - key: cke.cybozu.com/role
        operator: In
        values: ["cs"]
      - key: node-role.kubernetes.io/spare
        operator: DoesNotExist
  bgpInstances:
  - name: "cilium-lb-bgp"
    localASN: 64698
    peers:
    - name: "peer-to-bird-on-node"
      peerASN: 64699
      peerAddress: 127.0.0.1
      peerConfigRef:
        name: "cilium-lb-bgp-peer-config"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-lb-bgp-peer-config
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "cilium-lb-bgp"
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-default
  labels:
    advertise: cilium-lb-bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - {key: "lbipam.neco.cybozu.io/address-pool", operator: NotIn, values: ["internet", "internet-cn", "bastion"]}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-bastion
  labels:
    advertise: cilium-lb-bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["bastion"]}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-internet
  labels:
    advertise: cilium-lb-bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["internet"]}
---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: lb-internet-cn
  labels:
    advertise: cilium-lb-bgp
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - {key: "lbipam.neco.cybozu.io/address-pool", operator: In, values: ["internet-cn"]}

