apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  serviceSubnet: 10.68.0.0/16
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.0.2"
        taints: []
      localAPIEndpoint:
        advertiseAddress: "10.69.0.2"
    labels:
      rack: rack0
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.0.3"
    labels:
      rack: rack0
      mooring.hanapeida.link/advertise: "true"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-ip: "10.69.0.4"
    labels:
      rack: rack0
