apiVersion: hanapedia.link/v1alpha1
kind: NATConfig
metadata:
  name: domestic1
spec:
  externalIPPool:
    - 192.168.10.0/32
  portRangeSize: 100
  targetCIDRs:
    - 192.168.10.0/24
  podSelector:
    matchLabels:
      app: domestic1-client
