// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RevnatXdpLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type RevnatXdpNatMapKey struct {
	_     structs.HostLayout
	IpA   uint32
	IpB   uint32
	PortA uint16
	PortB uint16
	Proto uint8
	Kind  uint8
	_     [2]byte
}

type RevnatXdpNatMapVal struct {
	_         structs.HostLayout
	NatIp     uint32
	Port      uint16
	_         [2]byte
	ClosingNs uint64
}

type RevnatXdpTargetCidrVal struct {
	_         structs.HostLayout
	Addr      uint32
	Prefixlen uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RevnatXdpMapExtIpPool           = "ext_ip_pool"
	RevnatXdpMapNatMap              = "nat_map"
	RevnatXdpMapPortRangeInner      = "port_range_inner"
	RevnatXdpMapPortRangeLookupIcmp = "port_range_lookup_icmp"
	RevnatXdpMapPortRangeLookupTcp  = "port_range_lookup_tcp"
	RevnatXdpMapPortRangeLookupUdp  = "port_range_lookup_udp"
	RevnatXdpMapTargetCidrs         = "target_cidrs"
	RevnatXdpProgRevnatXdp          = "revnat_xdp"
)

// LoadRevnatXdp returns the embedded CollectionSpec for RevnatXdp.
func LoadRevnatXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RevnatXdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RevnatXdp: %w", err)
	}

	return spec, err
}

// LoadRevnatXdpObjects loads RevnatXdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RevnatXdpObjects
//	*RevnatXdpPrograms
//	*RevnatXdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRevnatXdpObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRevnatXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RevnatXdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatXdpSpecs struct {
	RevnatXdpProgramSpecs
	RevnatXdpMapSpecs
	RevnatXdpVariableSpecs
}

// RevnatXdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatXdpProgramSpecs struct {
	RevnatXdp *ebpf.ProgramSpec `ebpf:"revnat_xdp"`
}

// RevnatXdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatXdpMapSpecs struct {
	ExtIpPool           *ebpf.MapSpec `ebpf:"ext_ip_pool"`
	NatMap              *ebpf.MapSpec `ebpf:"nat_map"`
	PortRangeInner      *ebpf.MapSpec `ebpf:"port_range_inner"`
	PortRangeLookupIcmp *ebpf.MapSpec `ebpf:"port_range_lookup_icmp"`
	PortRangeLookupTcp  *ebpf.MapSpec `ebpf:"port_range_lookup_tcp"`
	PortRangeLookupUdp  *ebpf.MapSpec `ebpf:"port_range_lookup_udp"`
	TargetCidrs         *ebpf.MapSpec `ebpf:"target_cidrs"`
}

// RevnatXdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatXdpVariableSpecs struct{}

// RevnatXdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatXdpObjects struct {
	RevnatXdpPrograms
	RevnatXdpMaps
	RevnatXdpVariables
}

func (o *RevnatXdpObjects) Close() error {
	return _RevnatXdpClose(
		&o.RevnatXdpPrograms,
		&o.RevnatXdpMaps,
	)
}

// RevnatXdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatXdpMaps struct {
	ExtIpPool           *ebpf.Map `ebpf:"ext_ip_pool"`
	NatMap              *ebpf.Map `ebpf:"nat_map"`
	PortRangeInner      *ebpf.Map `ebpf:"port_range_inner"`
	PortRangeLookupIcmp *ebpf.Map `ebpf:"port_range_lookup_icmp"`
	PortRangeLookupTcp  *ebpf.Map `ebpf:"port_range_lookup_tcp"`
	PortRangeLookupUdp  *ebpf.Map `ebpf:"port_range_lookup_udp"`
	TargetCidrs         *ebpf.Map `ebpf:"target_cidrs"`
}

func (m *RevnatXdpMaps) Close() error {
	return _RevnatXdpClose(
		m.ExtIpPool,
		m.NatMap,
		m.PortRangeInner,
		m.PortRangeLookupIcmp,
		m.PortRangeLookupTcp,
		m.PortRangeLookupUdp,
		m.TargetCidrs,
	)
}

// RevnatXdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatXdpVariables struct{}

// RevnatXdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatXdpPrograms struct {
	RevnatXdp *ebpf.Program `ebpf:"revnat_xdp"`
}

func (p *RevnatXdpPrograms) Close() error {
	return _RevnatXdpClose(
		p.RevnatXdp,
	)
}

func _RevnatXdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed revnatxdp_bpfel.o
var _RevnatXdpBytes []byte
