// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RevnatIngressLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type RevnatIngressNatMapKey struct {
	_     structs.HostLayout
	IpA   uint32
	IpB   uint32
	PortA uint16
	PortB uint16
	Proto uint8
	Kind  uint8
	_     [2]byte
}

type RevnatIngressNatMapVal struct {
	_         structs.HostLayout
	NatIp     uint32
	Port      uint16
	_         [2]byte
	ClosingNs uint64
}

type RevnatIngressTargetCidrVal struct {
	_         structs.HostLayout
	Addr      uint32
	Prefixlen uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RevnatIngressMapExtIpPool           = "ext_ip_pool"
	RevnatIngressMapNatMap              = "nat_map"
	RevnatIngressMapPortRangeInner      = "port_range_inner"
	RevnatIngressMapPortRangeLookupIcmp = "port_range_lookup_icmp"
	RevnatIngressMapPortRangeLookupTcp  = "port_range_lookup_tcp"
	RevnatIngressMapPortRangeLookupUdp  = "port_range_lookup_udp"
	RevnatIngressMapTargetCidrs         = "target_cidrs"
	RevnatIngressProgRevnatIngress      = "revnat_ingress"
)

// LoadRevnatIngress returns the embedded CollectionSpec for RevnatIngress.
func LoadRevnatIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RevnatIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RevnatIngress: %w", err)
	}

	return spec, err
}

// LoadRevnatIngressObjects loads RevnatIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RevnatIngressObjects
//	*RevnatIngressPrograms
//	*RevnatIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRevnatIngressObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRevnatIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RevnatIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressSpecs struct {
	RevnatIngressProgramSpecs
	RevnatIngressMapSpecs
	RevnatIngressVariableSpecs
}

// RevnatIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressProgramSpecs struct {
	RevnatIngress *ebpf.ProgramSpec `ebpf:"revnat_ingress"`
}

// RevnatIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressMapSpecs struct {
	ExtIpPool           *ebpf.MapSpec `ebpf:"ext_ip_pool"`
	NatMap              *ebpf.MapSpec `ebpf:"nat_map"`
	PortRangeInner      *ebpf.MapSpec `ebpf:"port_range_inner"`
	PortRangeLookupIcmp *ebpf.MapSpec `ebpf:"port_range_lookup_icmp"`
	PortRangeLookupTcp  *ebpf.MapSpec `ebpf:"port_range_lookup_tcp"`
	PortRangeLookupUdp  *ebpf.MapSpec `ebpf:"port_range_lookup_udp"`
	TargetCidrs         *ebpf.MapSpec `ebpf:"target_cidrs"`
}

// RevnatIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressVariableSpecs struct{}

// RevnatIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressObjects struct {
	RevnatIngressPrograms
	RevnatIngressMaps
	RevnatIngressVariables
}

func (o *RevnatIngressObjects) Close() error {
	return _RevnatIngressClose(
		&o.RevnatIngressPrograms,
		&o.RevnatIngressMaps,
	)
}

// RevnatIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressMaps struct {
	ExtIpPool           *ebpf.Map `ebpf:"ext_ip_pool"`
	NatMap              *ebpf.Map `ebpf:"nat_map"`
	PortRangeInner      *ebpf.Map `ebpf:"port_range_inner"`
	PortRangeLookupIcmp *ebpf.Map `ebpf:"port_range_lookup_icmp"`
	PortRangeLookupTcp  *ebpf.Map `ebpf:"port_range_lookup_tcp"`
	PortRangeLookupUdp  *ebpf.Map `ebpf:"port_range_lookup_udp"`
	TargetCidrs         *ebpf.Map `ebpf:"target_cidrs"`
}

func (m *RevnatIngressMaps) Close() error {
	return _RevnatIngressClose(
		m.ExtIpPool,
		m.NatMap,
		m.PortRangeInner,
		m.PortRangeLookupIcmp,
		m.PortRangeLookupTcp,
		m.PortRangeLookupUdp,
		m.TargetCidrs,
	)
}

// RevnatIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressVariables struct{}

// RevnatIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressPrograms struct {
	RevnatIngress *ebpf.Program `ebpf:"revnat_ingress"`
}

func (p *RevnatIngressPrograms) Close() error {
	return _RevnatIngressClose(
		p.RevnatIngress,
	)
}

func _RevnatIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed revnatingress_bpfel.o
var _RevnatIngressBytes []byte
