// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type RevnatIngressLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type RevnatIngressNatKey struct {
	_          structs.HostLayout
	PodIp      uint32
	NatPort    uint16
	_          [2]byte
	ServerIp   uint32
	ServerPort uint16
	Proto      uint8
	Pad        [3]uint8
	_          [2]byte
}

type RevnatIngressNatVal struct {
	_       structs.HostLayout
	PodPort uint16
}

type RevnatIngressPortKey struct {
	_       structs.HostLayout
	ExtIp   uint32
	NatPort uint16
	Pad     [2]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	RevnatIngressMapExtIpPool       = "ext_ip_pool"
	RevnatIngressMapNatTable        = "nat_table"
	RevnatIngressMapPortRangeLookup = "port_range_lookup"
	RevnatIngressMapTargetCidrs     = "target_cidrs"
	RevnatIngressProgRevnatIngress  = "revnat_ingress"
)

// LoadRevnatIngress returns the embedded CollectionSpec for RevnatIngress.
func LoadRevnatIngress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RevnatIngressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load RevnatIngress: %w", err)
	}

	return spec, err
}

// LoadRevnatIngressObjects loads RevnatIngress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*RevnatIngressObjects
//	*RevnatIngressPrograms
//	*RevnatIngressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadRevnatIngressObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadRevnatIngress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// RevnatIngressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressSpecs struct {
	RevnatIngressProgramSpecs
	RevnatIngressMapSpecs
	RevnatIngressVariableSpecs
}

// RevnatIngressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressProgramSpecs struct {
	RevnatIngress *ebpf.ProgramSpec `ebpf:"revnat_ingress"`
}

// RevnatIngressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressMapSpecs struct {
	ExtIpPool       *ebpf.MapSpec `ebpf:"ext_ip_pool"`
	NatTable        *ebpf.MapSpec `ebpf:"nat_table"`
	PortRangeLookup *ebpf.MapSpec `ebpf:"port_range_lookup"`
	TargetCidrs     *ebpf.MapSpec `ebpf:"target_cidrs"`
}

// RevnatIngressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type RevnatIngressVariableSpecs struct {
}

// RevnatIngressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressObjects struct {
	RevnatIngressPrograms
	RevnatIngressMaps
	RevnatIngressVariables
}

func (o *RevnatIngressObjects) Close() error {
	return _RevnatIngressClose(
		&o.RevnatIngressPrograms,
		&o.RevnatIngressMaps,
	)
}

// RevnatIngressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressMaps struct {
	ExtIpPool       *ebpf.Map `ebpf:"ext_ip_pool"`
	NatTable        *ebpf.Map `ebpf:"nat_table"`
	PortRangeLookup *ebpf.Map `ebpf:"port_range_lookup"`
	TargetCidrs     *ebpf.Map `ebpf:"target_cidrs"`
}

func (m *RevnatIngressMaps) Close() error {
	return _RevnatIngressClose(
		m.ExtIpPool,
		m.NatTable,
		m.PortRangeLookup,
		m.TargetCidrs,
	)
}

// RevnatIngressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressVariables struct {
}

// RevnatIngressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadRevnatIngressObjects or ebpf.CollectionSpec.LoadAndAssign.
type RevnatIngressPrograms struct {
	RevnatIngress *ebpf.Program `ebpf:"revnat_ingress"`
}

func (p *RevnatIngressPrograms) Close() error {
	return _RevnatIngressClose(
		p.RevnatIngress,
	)
}

func _RevnatIngressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed revnatingress_bpfel.o
var _RevnatIngressBytes []byte
