// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SnatEgressLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type SnatEgressNatConfigKey struct {
	_             structs.HostLayout
	PodIp         uint32
	CidrAddr      uint32
	CidrPrefixlen uint32
}

type SnatEgressNatConfigVal struct {
	_               structs.HostLayout
	PortRangeAllocs [256]struct {
		_         structs.HostLayout
		ExtIp     uint32
		PortStart uint16
		PortEnd   uint16
	}
	Count uint32
}

type SnatEgressNatMapKey struct {
	_     structs.HostLayout
	IpA   uint32
	IpB   uint32
	PortA uint16
	PortB uint16
	Proto uint8
	Kind  uint8
	_     [2]byte
}

type SnatEgressNatMapVal struct {
	_         structs.HostLayout
	NatIp     uint32
	Port      uint16
	_         [2]byte
	ClosingNs uint64
}

type SnatEgressTargetCidrVal struct {
	_         structs.HostLayout
	Addr      uint32
	Prefixlen uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SnatEgressMapNatConfig   = "nat_config"
	SnatEgressMapNatMap      = "nat_map"
	SnatEgressMapTargetCidrs = "target_cidrs"
	SnatEgressProgSnatEgress = "snat_egress"
)

// LoadSnatEgress returns the embedded CollectionSpec for SnatEgress.
func LoadSnatEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SnatEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SnatEgress: %w", err)
	}

	return spec, err
}

// LoadSnatEgressObjects loads SnatEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SnatEgressObjects
//	*SnatEgressPrograms
//	*SnatEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSnatEgressObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSnatEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SnatEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressSpecs struct {
	SnatEgressProgramSpecs
	SnatEgressMapSpecs
	SnatEgressVariableSpecs
}

// SnatEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressProgramSpecs struct {
	SnatEgress *ebpf.ProgramSpec `ebpf:"snat_egress"`
}

// SnatEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressMapSpecs struct {
	NatConfig   *ebpf.MapSpec `ebpf:"nat_config"`
	NatMap      *ebpf.MapSpec `ebpf:"nat_map"`
	TargetCidrs *ebpf.MapSpec `ebpf:"target_cidrs"`
}

// SnatEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressVariableSpecs struct{}

// SnatEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressObjects struct {
	SnatEgressPrograms
	SnatEgressMaps
	SnatEgressVariables
}

func (o *SnatEgressObjects) Close() error {
	return _SnatEgressClose(
		&o.SnatEgressPrograms,
		&o.SnatEgressMaps,
	)
}

// SnatEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressMaps struct {
	NatConfig   *ebpf.Map `ebpf:"nat_config"`
	NatMap      *ebpf.Map `ebpf:"nat_map"`
	TargetCidrs *ebpf.Map `ebpf:"target_cidrs"`
}

func (m *SnatEgressMaps) Close() error {
	return _SnatEgressClose(
		m.NatConfig,
		m.NatMap,
		m.TargetCidrs,
	)
}

// SnatEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressVariables struct{}

// SnatEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressPrograms struct {
	SnatEgress *ebpf.Program `ebpf:"snat_egress"`
}

func (p *SnatEgressPrograms) Close() error {
	return _SnatEgressClose(
		p.SnatEgress,
	)
}

func _SnatEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed snategress_bpfel.o
var _SnatEgressBytes []byte
