// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type SnatEgressLpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type SnatEgressNatKey struct {
	_          structs.HostLayout
	PodIp      uint32
	ServerIp   uint32
	NatPort    uint16
	ServerPort uint16
}

type SnatEgressNatVal struct {
	_       structs.HostLayout
	PodPort uint16
}

type SnatEgressSessionKey struct {
	_          structs.HostLayout
	PodIp      uint32
	PodPort    uint16
	_          [2]byte
	ServerIp   uint32
	ServerPort uint16
	Proto      uint8
	Pad        [3]uint8
	_          [2]byte
}

type SnatEgressSessionVal struct {
	_       structs.HostLayout
	ExtIp   uint32
	NatPort uint16
	_       [2]byte
}

type SnatEgressSnatConfigVal struct {
	_           structs.HostLayout
	Allocations [16]struct {
		_         structs.HostLayout
		ExtIp     uint32
		PortStart uint16
		PortEnd   uint16
		NextPort  uint32
	}
	Count uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	SnatEgressMapNatTableIcmp     = "nat_table_icmp"
	SnatEgressMapNatTableTcp      = "nat_table_tcp"
	SnatEgressMapNatTableUdp      = "nat_table_udp"
	SnatEgressMapOutboundSessions = "outbound_sessions"
	SnatEgressMapSnatConfig       = "snat_config"
	SnatEgressMapTargetCidrs      = "target_cidrs"
	SnatEgressProgSnatEgress      = "snat_egress"
)

// LoadSnatEgress returns the embedded CollectionSpec for SnatEgress.
func LoadSnatEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SnatEgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load SnatEgress: %w", err)
	}

	return spec, err
}

// LoadSnatEgressObjects loads SnatEgress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*SnatEgressObjects
//	*SnatEgressPrograms
//	*SnatEgressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadSnatEgressObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadSnatEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// SnatEgressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressSpecs struct {
	SnatEgressProgramSpecs
	SnatEgressMapSpecs
	SnatEgressVariableSpecs
}

// SnatEgressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressProgramSpecs struct {
	SnatEgress *ebpf.ProgramSpec `ebpf:"snat_egress"`
}

// SnatEgressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressMapSpecs struct {
	NatTableIcmp     *ebpf.MapSpec `ebpf:"nat_table_icmp"`
	NatTableTcp      *ebpf.MapSpec `ebpf:"nat_table_tcp"`
	NatTableUdp      *ebpf.MapSpec `ebpf:"nat_table_udp"`
	OutboundSessions *ebpf.MapSpec `ebpf:"outbound_sessions"`
	SnatConfig       *ebpf.MapSpec `ebpf:"snat_config"`
	TargetCidrs      *ebpf.MapSpec `ebpf:"target_cidrs"`
}

// SnatEgressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type SnatEgressVariableSpecs struct {
}

// SnatEgressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressObjects struct {
	SnatEgressPrograms
	SnatEgressMaps
	SnatEgressVariables
}

func (o *SnatEgressObjects) Close() error {
	return _SnatEgressClose(
		&o.SnatEgressPrograms,
		&o.SnatEgressMaps,
	)
}

// SnatEgressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressMaps struct {
	NatTableIcmp     *ebpf.Map `ebpf:"nat_table_icmp"`
	NatTableTcp      *ebpf.Map `ebpf:"nat_table_tcp"`
	NatTableUdp      *ebpf.Map `ebpf:"nat_table_udp"`
	OutboundSessions *ebpf.Map `ebpf:"outbound_sessions"`
	SnatConfig       *ebpf.Map `ebpf:"snat_config"`
	TargetCidrs      *ebpf.Map `ebpf:"target_cidrs"`
}

func (m *SnatEgressMaps) Close() error {
	return _SnatEgressClose(
		m.NatTableIcmp,
		m.NatTableTcp,
		m.NatTableUdp,
		m.OutboundSessions,
		m.SnatConfig,
		m.TargetCidrs,
	)
}

// SnatEgressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressVariables struct {
}

// SnatEgressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadSnatEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type SnatEgressPrograms struct {
	SnatEgress *ebpf.Program `ebpf:"snat_egress"`
}

func (p *SnatEgressPrograms) Close() error {
	return _SnatEgressClose(
		p.SnatEgress,
	)
}

func _SnatEgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed snategress_bpfel.o
var _SnatEgressBytes []byte
